<fieldset class="fieldset create account" data-hasrequired="<?php /* @escapeNotVerified */ echo __('* Required Fields') ?>">
    <legend class="legend"><span><?php /* @escapeNotVerified */ echo __('Additional Information') ?></span></legend>
    <p>
    <div class="field linkedin_profile required">
        <label for="linkedin_profile" class="label"><span><?php
                echo __('Linkedin') ?></span></label>
        <div class="control">
            <input type="text" name="linkedin_profile" id="linkedin_profile" title="<?php echo __('Linkedin') ?>" class="input-text" data-validate="{required:true}">
        </div>
    </div>
    </p>
</fieldset>
